### ISSUE TITLE
JSP Wiki resource should work

### ISSUE THREAD

**Issue by michaelwechner** [wyona/yanel#69]
when requesting

http://127.0.0.1:8080/yanel/yanel-website/references.html

then we currently receive the following error:

43583837 2014-03-25 08:26:15,761 +0100 [http-bio-8080-exec-10] WARN  org.wyona.yanel.core.Yanel.getBeanFactory():166  - DEPRECATED
43583838 2014-03-25 08:26:15,762 +0100 [http-bio-8080-exec-10] ERROR org.wyona.yanel.impl.resources.WikiResource.getView():210  - org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jspWikiParser' is defined
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jspWikiParser' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:355)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:800)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:237)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:156)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:642)
	at org.wyona.yanel.impl.resources.WikiResource.getView(WikiResource.java:119)
	at org.wyona.yanel.impl.resources.WikiResource.getView(WikiResource.java:228)
	at org.wyona.yanel.servlet.YanelServlet.getContent(YanelServlet.java:599)
	at org.wyona.yanel.servlet.YanelServlet.doGet(YanelServlet.java:494)
	at org.wyona.yanel.servlet.YanelServlet.service(YanelServlet.java:390)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.wyona.yanel.servlet.communication.YanelFilter.doFilter(YanelFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:680)

**Comment by michaelwechner** [comment]
We have replaced getBeanFactory() with getWikiParser() and it works now again

http://www.yanel.org/references.html
